#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axm.Xrm.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum axm_ServicetypeNn
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All inclusive", 0)]
		AllInclusive = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Another type", 3)]
		AnotherType = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Half inclusive", 1)]
		HalfInclusive = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not inclusive", 2)]
		NotInclusive = 2,
	}
}
#pragma warning restore CS1591
